name: modis-readers
channels:
  - conda-forge
  - nodefaults
dependencies:
  - h5netcdf
  - netcdf4
  - numpy
  - pip
  - pre-commit
  - rasterio
  - satpy
  - xarray
  - pyhdf
  - rioxarray
  - ipykernel
  - fsspec
  - earthaccess
